-- 1
SELECT FRS_NOM FROM Fournisseur ;
-- 2
SELECT DISTINCT CLT_LOC AS localite FROM CLIENT;
-- 3
SELECT CLT_NOM, CLT_PRENOM FROM CLIENT WHERE CLT_LOC="PARIS";
-- 4
SELECT AVG(ART_POIDS) AS moyenne FROM ARTICLE;
-- 5
SELECT MAX(ART_PV) AS prix_max FROM ARTICLE;
-- 6
SELECT ART_NUM, ART_NOM, ART_NOM, ART_COUL FROM ARTICLE WHERE ART_COUL = "ROUGE";
-- 7
SELECT ART_NUM, ART_NOM, ART_COUL FROM ARTICLE WHERE (ART_COUL = "ROUGE" AND ART_POIDS > 100) OR ART_COUL = "VERT";
-- 8
SELECT ART_NUM, ART_NOM, ART_POIDS, ART_PA FROM ARTICLE WHERE ART_POIDS <= 100 ORDER BY ART_PA ASC;
-- 9
SELECT AVG(ART_PV) AS pvmoyen, MAX(ART_PV - ART_PA) AS margemax, (MAX(ART_PV)-MIN(ART_PV)) AS dpmax FROM ARTICLE WHERE ART_COUL is not NULL;
-- 10
SELECT ART_NOM, ART_COUL, ART_POIDS, FRS_NOM FROM ARTICLE JOIN FOURNISSEUR ON ART_FRS = FRS_NUM WHERE ART_COUL = "ROUGE";
-- 11
SELECT CLT_NOM FROM CLIENT JOIN COMMANDE ON CLT_NUM = CMD_CLT JOIN ARTICLE ON ART_NUM = CMD_NUM WHERE ART_NUM = "A02";
-- 12
SELECT FRS_NOM 
FROM FOURNISSEUR 
JOIN ARTICLE  ON ART_FRS  = FRS_NUM
JOIN COMMANDE ON ART_NUM = CMD_NUM
JOIN CLIENT ON CMD_CLT = CLT_NUM
WHERE CLT_NUM = 'C01';
-- 13
SELECT SUM(ART_POIDS) AS masse FROM ARTICLE JOIN COMMANDE ON ART_NUM = CMD_NUM JOIN CLIENT ON CMD_CLT = CLT_NUM WHERE CLT_LOC = "LYON";
-- 14
SELECT CLT_PRENOM, CLT_NOM
-- 15
SELECT ART_COUL, AVG(ART_PV) AS pv_moyen FROM ARTICLE;



